---
# Docker hosts specific variables
docker_users:
  - ubuntu
  - deploy

docker_daemon_options:
  storage-driver: "overlay2"
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "5"
  default-address-pools:
    - base: "172.17.0.0/16"
      size: 24
